name: 'Custom CD'

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: '7.0.x'
      - name: Publish Project
        run: dotnet publish -o output/ -c Release

      - name: Echo Output
        run: dir output
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          name: 'release'
          type: 'zip'
          path: output/
      - name: Echo Output (after Zip)
        run: dir output