name: 'Custom CD'

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: '7.0.x'
      - name: Publish Project
        run: dotnet publish -o output/ -c Release
      - name: Read current Version
        id: version
        uses: juliangruber/read-file-action@v1.1.6
        with:
          path: ./VERSION.txt
      - name: Archive Output
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r release-${{ steps.version.outputs.content }}.zip output/
      - name: Upload Nextcloud
        uses: trympet/nextcloud-artifacts-action@v2.0.0
        with:
          token: ${{ secrets.PAT }}
          name: 'release-${{ steps.version.outputs.content }}.zip'
          path: 'release-${{ steps.version.outputs.content }}.zip'
          nextcloud-url: 'https://cloud.saveapis.com'
          nextcloud-username: ${{ secrets.NEXTCLOUD_USERNAME }}
          nextcloud-password: ${{ secrets.NEXTCLOUD_PASSWORD }}